apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis-db
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
      - name: postgis
        image: postgis/postgis:16-3.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_USER
          value: "mp"
        - name: POSTGRES_DB
          value: "global"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgis-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgis-storage
        persistentVolumeClaim:
          claimName: postgis-pvc
