apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi  # Adjust size as necessary
  selector:
    matchLabels:
      type: local  # Matches the label from the PersistentVolume