apiVersion: v1
kind: Service
metadata:
  name: postgis-service
spec:
  selector:
    app: postgis
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30500
  type: NodePort