# Default values for postgis-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgis/postgis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "16-3.4"

service:
  type: NodePort
  port: 5432
  nodePort: 30500

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true    # or false, depending on your use case
  name: ""        # Optional: Leave blank to use the default name

autoscaling:
  enabled: false
pgPassword: admin
envSecrets:
  - name: my-postgres-secret

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  hostPath: /home/mp/postgres_data # External path on  WSL
  mountPath: /var/lib/postgresql/data # Internal path inside the container